### ISSUE TITLE
[Bug]: SearchIterator missing 1 required positional argument 'connection' when upgrading pymilvus to 2.4.0.dev92

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 417a512
- Deployment mode(standalone or cluster):standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2):2.4.0.dev92
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

SearchIterator missing 1 required positional argument 'connection' when upgrading pymilvus to 2.4.0.dev92.
```
[2023-07-13 17:19:27 - ERROR - ci_test]: Traceback (most recent call last):
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
    res = func(*args, **_kwargs)
  File "/Users/zilliz/nico/milvus/tests/python_client/utils/api_request.py", line 57, in api_request
    return func(*arg, **kwargs)
  File "/Users/zilliz/virtual-environment/milvus2/lib/python3.10/site-packages/pymilvus/orm/collection.py", line 814, in search_iterator
    return SearchIterator(
TypeError: SearchIterator.__init__() missing 1 required positional argument: 'connection'
 (api_request.py:39)
[2023-07-13 17:19:27 - ERROR - ci_test]: (api_response) : SearchIterator.__init__() missing 1 required positional argument: 'connection' (api_request.py:40)

```

### Expected Behavior

pass

### Milvus Log

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-25479/7/pipeline/129/

**Comment by NicoYuan1986** [comment]
2.4.0.dev95  same error

**Comment by XuanYang-cn** [comment]
Please try dev100
/assign @NicoYuan1986 
/unassign

**Comment by NicoYuan1986** [comment]
Fixed.
