### ISSUE TITLE
[Bug]: master proxy test binary fails to compile after #52544 landed on top of #53023

### ISSUE THREAD

**Issue by bigsheeper** [milvus-io/milvus#53242]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```
- Milvus version: master (11ed73e3fb)
```

### Current Behavior

`make static-check` (golangci-lint typecheck with `dynamic,test` tags) fails on master, so every PR's `ci-v2/build-ut-cov` Code-Check stage fails and no `internal/proxy` unit test runs:

```
internal/proxy/impl_test.go:1807:21: undefined: newTaskScheduler
internal/proxy/task_import_test.go:454:7: task.metaCache undefined (type *importTask has no field or method metaCache, but does have field MetaCache) (typecheck)
```

First failing master build: milvus-build-ut-ciloop-pipeline #29782 (commit dd75544).

### Expected Behavior

`internal/proxy` tests compile on master.

### Steps To Reproduce

```
GOWORK=off go vet -tags dynamic,test ./internal/proxy/
```

### Anything else?

#53023 (merged 2026-09-04) moved the proxy task scheduler into `internal/proxy/scheduler` and renamed `newTaskScheduler` -> `scheduler.NewTaskScheduler` and `baseTask.metaCache` -> `MetaCache`. #52544 (merged 2026-09-07) was based on pre-#53023 code and re-introduced both old identifiers in the two test files. The two PRs touched different lines, so the merge was textually clean.
