### ISSUE TITLE
Master branch build broken: QueryContext::element_level_query() does not exist

### ISSUE THREAD

**Issue by xiaofan-luan** [milvus-io/milvus#48253]
## Summary

The master branch fails to compile after PR #47906 was merged. The C++ code in `ExecPlanNodeVisitor.cpp:341` calls `query_context->element_level_query()`, but `QueryContext` has no such method.

## Error

```
internal/core/src/query/ExecPlanNodeVisitor.cpp:341:28: error: 'using element_type = class milvus::exec::QueryContext' has no member named 'element_level_query'
```

## Root Cause

PR #47906 (feat: impl StructArray -- support element-level query) introduced a call to a non-existent method. The correct method should be `bitset_is_element_level()` which is defined in `QueryContext.h:374`.

## Impact

- Master branch cannot compile
- All PR CI builds that rebase on latest master fail at the build stage

@SpadeA-Tang
