### ISSUE TITLE
[Bug]: Suspend/Resume does not change node state???

### ISSUE THREAD

**Issue by cocktail828** [milvus-io/milvus#40896]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:2.5.0 and latest
- Deployment mode(standalone or cluster): cluster
- MQ type(rocksmq, pulsar or kafka):    pulsar
- SDK version(e.g. pymilvus v2.0.0rc2): not related
- OS(Ubuntu or CentOS): centos
- CPU/Memory: not related
- GPU: not related
- Others: not related
```

### Operation:
Nowdays, I trying to do Milvus upgrade via management API.
```bash
curl --request POST \
--url http://${hostport}/management/querycoord/node/suspend \
--header 'content-type: application/x-www-form-urlencoded' \
--data node_id=${node_id}
```
I have checked the 'Suspend/Resume' API. After send the request the specified querynode will be marked as 'suspend'. However the state will always be 'normal' at version 2.5 and latest.

### Review the source code

I have browser the source code (internal/querycoordv2/session/node_manager.go:95) of milvus latest version and foind that,  the `qc` does not perform state change, the related code has been removed.
```
type Manager interface {
Add(node *NodeInfo)
Stopping(nodeID int64)
Remove(nodeID int64)
Get(nodeID int64) *NodeInfo
GetAll() []*NodeInfo

Suspend(nodeID int64) error // NodeManager does not implement the method
Resume(nodeID int64) error // NodeManager does not implement the method
}
```

### Effect
Not sure. I am still check what the state will affect if `qc` does not perform state change. 

### Expected Behavior

1. The specified querynode will be marked as 'suspend' after sending the Suspend API
2. The specified querynode will be marked as 'normal' after sending the Resume API

### Steps To Reproduce

```markdown

```

**Comment by xiaofan-luan** [comment]
@cocktail828 
the code should be still useful.

instead of handle it immeditaly.
Resource Manger will handle it by HandleNodeDown and then Replica Manager handle the suspended node in a replica asyncly.

Let me know if you found  case which not works as expected

**Comment by yanliang567** [comment]
/assign @congqixia 
please help to take a look
/unassign

**Comment by cocktail828** [comment]
Thanks for your reply. I'm expecting it to work fine in version 2.5.8.
And please notice me if there is a misuse .


To be seriously, I have some evidence to proof that this is a bug.

1. check var reference
```bash
grep --exclude="*_test.go" --exclude="*.js" -nrwi suspend ./internal
# there is no code refer or set the 'suspend' state
```

2. check whether there is any code that will call SetState
```bash
grep --exclude="*_test.go" --exclude="*.js" -nrw SetState ./internal | grep query -i
# Unfortunately, there is no code like SetState(NodeStateSuspend) found
# moreover, the `state` field is unexport, users can only change the state via method `SetState`.
# The ListQueryNode API retrieves the status info of the querynode through the `session.NodeManager` state field.

type NodeInfo struct {
    stats
    mu sync.RWMutex
    immutableInfo ImmutableNodeInfo
    state State           // not export
    lastHeartbeat *atomic.Int64
}
```

**Comment by xiaofan-luan** [comment]
As fa as a know, the easiest way to decommission  a node is simply call kill to it's process.

the node will be put into stopping state.

**Comment by xiaofan-luan** [comment]
right now we don't use suspend state for any place.

there is a stopping state, doing the similar functionality here.

**Comment by cocktail828** [comment]
> As fa as a know, the easiest way to decommission a node is simply call kill to it's process.
>
> the node will be put into stopping state.

Sure, but I am no trying to stop a querynode, but upgrade it.

> right now we don't use suspend state for any place.
>
> there is a stopping state, doing the similar functionality here.

Yep, not in any other place, but milvus version upgrading.

The same API works on v2.4.9 and the the following code mark the querynode into Suspend state.
https://github.com/milvus-io/milvus/blob/4e098f1b23db9639d1e1948eacc052dba92f5163/internal/querycoordv2/ops_services.go#L215
```bash
# API: /management/querycoord/node/list
{
    "nodeInfos": [
        {
            "ID": 37,
            "address": "....",
            "state": "Suspend" // the expect state indicates the suspend request has been handled successfully
                                          // I have test the same API with version v2.4.9, and it works.
        }
    ]
}
```

The suspend state is required and meaningful. 
- The suspend API always returns success no mater what has happend insight `ResourceManager.HandleNodeDown`.
- It indicates the suspend request(/management/querycoord/node/suspend) has been handled successfully.
- The querycoord balancer(channel/segment) also check the querynode state before making any balance plan.
- The suspended querynode should have something different with the others.

**Comment by xiaofan-luan** [comment]
> the querynode into Suspend state.
> 
> [milvus/internal/querycoordv2/ops_services.go](https://github.com/milvus-io/milvus/blob/4e098f1b23db9639d1e1948eacc052dba92f5163/internal/querycoordv2/ops_services.go#L215)
> 
> Line 215 in [4e098f1](/milvus-io/milvus/commit/4e098f1b23db9639d1e1948eacc052dba92f5163)
> 
>  err := s.nodeMgr.Suspend(req.GetNodeID()) 
> # API: /management/querycoord/node/list

I think it's just because we are not using suspending state anymore.
Stopping is acting the same way as suspending so we merge the two state.

**Comment by xiaofan-luan** [comment]
did you tried and it's not working on 2.5 or above?
@weiliu1031 can you help on this?

**Comment by weiliu1031** [comment]
> did you tried and it's not working on 2.5 or above? [@weiliu1031](https://github.com/weiliu1031) can you help on this?

As previously mentioned, instead of maintaining a separate suspend state for nodes and relying on it throughout the codebase, Milvus now leverages the roNode implementation within replicas to achieve the same effect. The suspendNode and resumeNode APIs have been verified to function correctly and maintain expected behavior. Since these APIs are used for upgrade scheduling in Zilliz Cloud, everything is currently working as expected

**Comment by cocktail828** [comment]
> > did you tried and it's not working on 2.5 or above? [@weiliu1031](https://github.com/weiliu1031) can you help on this?
> 
> As previously mentioned, instead of maintaining a separate suspend state for nodes and relying on it throughout the codebase, Milvus now leverages the roNode implementation within replicas to achieve the same effect. The suspendNode and resumeNode APIs have been verified to function correctly and maintain expected behavior. Since these APIs are used for upgrade scheduling in Zilliz Cloud, everything is currently working as expected

@weiliu1031 Thanks for your help.
So, what the upgrade sequence should be now?
I am trying upgrade with following order and the target version is v2.5.6 (open source version).  Let me know, if something changes.
```bash
suspend balance -> suspend querynode[?] -> [transfer channels/segments] -> resume balance
                                         |
                    how to make sure the querynode has been suspend now?
                   (I used to judge the node status by polling the node/list api)
```

**Comment by weiliu1031** [comment]
> > > did you tried and it's not working on 2.5 or above? [@weiliu1031](https://github.com/weiliu1031) can you help on this?
> > 
> > 
> > As previously mentioned, instead of maintaining a separate suspend state for nodes and relying on it throughout the codebase, Milvus now leverages the roNode implementation within replicas to achieve the same effect. The suspendNode and resumeNode APIs have been verified to function correctly and maintain expected behavior. Since these APIs are used for upgrade scheduling in Zilliz Cloud, everything is currently working as expected
> 
> [@weiliu1031](https://github.com/weiliu1031) Thanks for your help. So, what the upgrade sequence should be now? I am trying upgrade with following order and the target version is v2.5.6 (open source version). Let me know, if something changes.
> 
> suspend balance -> suspend querynode[?] -> [transfer channels/segments] -> check querynode distribution -> resume balance
>                                          |
>                     how to make sure the querynode has been suspend now?
>                    (I used to judge the node status by polling the node/list api)

In fact, SuspendNode is merely a marking operation—once the API returns successfully, it guarantees that the suspend flag has been set, so no additional checks are needed. Based on the information above, it seems you've accessed some of my design documents and implemented a similar rolling upgrade process, which is quite impressive. However, you've introduced a dependency on the unnecessary ListQueryNode API, which has led to the current issue.

**Comment by cocktail828** [comment]
> 
> In fact, SuspendNode is merely a marking operation—once the API returns successfully, it guarantees that the suspend flag has been set, so no additional checks are needed. Based on the information above, it seems you've accessed some of my design documents and implemented a similar rolling upgrade process, which is quite impressive. However, you've introduced a dependency on the unnecessary ListQueryNode API, which has led to the current issue.

OK, fine!
One more question, I also find those two API. Should I pause `GC`, whiling do upgrading?
```bash
	RouteGcPause  = "/management/datacoord/garbage_collection/pause"
	RouteGcResume = "/management/datacoord/garbage_collection/resume"
```

**Comment by weiliu1031** [comment]
> > In fact, SuspendNode is merely a marking operation—once the API returns successfully, it guarantees that the suspend flag has been set, so no additional checks are needed. Based on the information above, it seems you've accessed some of my design documents and implemented a similar rolling upgrade process, which is quite impressive. However, you've introduced a dependency on the unnecessary ListQueryNode API, which has led to the current issue.
> 
> OK, fine! One more question, I also find those two API. Should I pause `GC`, whiling do upgrading?
> 
> 	RouteGcPause  = "/management/datacoord/garbage_collection/pause"
> 	RouteGcResume = "/management/datacoord/garbage_collection/resume"

No need for that

**Comment by weiliu1031** [comment]
should be solved

/unassign 
/assign @cocktail828
