### ISSUE TITLE
[Bug]: Fail to list indexes reporting Unexpected error when upgrading pymilvus to 2.2.14.dev14

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#25749]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 3ecf80c
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):    rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.14.dev14
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to list indexes reporting Unexpected error when upgrading pymilvus to 2.2.14.dev14.
```
[2023-07-19T07:20:24.630Z] [2023-07-19 07:20:14 - ERROR - pymilvus.decorators]: Unexpected error: [list_indexes], describe_index_request() missing 1 required positional argument: 'timestamp', <Time: {'RPC start': '2023-07-19 07:20:14.246247', 'Exception': '2023-07-19 07:20:14.246295'}> (decorators.py:143)
[2023-07-19T07:20:24.630Z] [2023-07-19 07:20:14 - ERROR - ci_test]: Traceback (most recent call last):
[2023-07-19T07:20:24.630Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 122, in handler
[2023-07-19T07:20:24.630Z]     return func(*args, **kwargs)
[2023-07-19T07:20:24.630Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 161, in handler
[2023-07-19T07:20:24.630Z]     return func(self, *args, **kwargs)
[2023-07-19T07:20:24.630Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 103, in handler
[2023-07-19T07:20:24.630Z]     raise e from e
[2023-07-19T07:20:24.630Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 68, in handler
[2023-07-19T07:20:24.630Z]     return func(*args, **kwargs)
[2023-07-19T07:20:24.630Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/client/grpc_handler.py", line 779, in list_indexes
[2023-07-19T07:20:24.630Z]     request = Prepare.describe_index_request(collection_name, "")
[2023-07-19T07:20:24.630Z] TypeError: describe_index_request() missing 1 required positional argument: 'timestamp'
[2023-07-19T07:20:24.630Z] 
[2023-07-19T07:20:24.630Z] The above exception was the direct cause of the following exception:
[2023-07-19T07:20:24.630Z] 
[2023-07-19T07:20:24.631Z] Traceback (most recent call last):
[2023-07-19T07:20:24.631Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 26, in inner_wrapper
[2023-07-19T07:20:24.631Z]     res = func(*args, **_kwargs)
[2023-07-19T07:20:24.631Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 57, in api_request
[2023-07-19T07:20:24.631Z]     return func(*arg, **kwargs)
[2023-07-19T07:20:24.631Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/index.py", line 84, in __init__
[2023-07-19T07:20:24.631Z]     indexes = conn.list_indexes(self._collection.name)
[2023-07-19T07:20:24.631Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/decorators.py", line 144, in handler
[2023-07-19T07:20:24.631Z]     raise MilvusException(message=f"Unexpected error, message=<{e!s}>") from e
[2023-07-19T07:20:24.631Z] pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=Unexpected error, message=<describe_index_request() missing 1 required positional argument: 'timestamp'>)>
[2023-07-19T07:20:24.631Z]  (api_request.py:39)
[2023-07-19T07:20:24.631Z] [2023-07-19 07:20:14 - ERROR - ci_test]: (api_response) : <MilvusException: (code=1, message=Unexpected error, message=<describe_index_request() missing 1 required positional argument: 'timestamp'>)> (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-25744/1/pipeline/167/

**Comment by XuanYang-cn** [comment]
/assign @NicoYuan1986 
/unassign @xiaocai2333 @XuanYang-cn 
 Please try pymilvus/2.2.14.dev15/

**Comment by NicoYuan1986** [comment]
Fixed.
