### ISSUE TITLE
[Bug]: Milvus build fail

### ISSUE THREAD

**Issue by cydrain** [milvus-io/milvus#39005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (ea339c1)
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others: gcc 9.4.0
```

### Current Behavior

see build error as following:
```
/home/caiyd/work/vec/milvus/internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp:925:29: error: use of deleted function ‘milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>& milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>::operator=(milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>&&) [with PolicyT = milvus::bitset::detail::VectorizedElementWiseBitsetPolicy<long unsigned int, milvus::bitset::detail::VectorizedDynamic>; ContainerT = folly::fbvector<unsigned char>; bool IsRangeCheckEnabled = true]’
  925 |                         res = std::move(func(index_ptr,
      |                         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
  926 |                                              sub_batch_size,
      |                                              ~~~~~~~~~~~~~~~
  927 |                                              value,
      |                                              ~~~~~~
  928 |                                              right_operand,
      |                                              ~~~~~~~~~~~~~~
  929 |                                              offsets));
      |                                              ~~~~~~~~~
/home/caiyd/work/vec/milvus/internal/core/src/exec/expression/BinaryArithOpEvalRangeExpr.cpp:938:29: error: use of deleted function ‘milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>& milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>::operator=(milvus::bitset::Bitset<PolicyT, ContainerT, IsRangeCheckEnabled>&&) [with PolicyT = milvus::bitset::detail::VectorizedElementWiseBitsetPolicy<long unsigned int, milvus::bitset::detail::VectorizedDynamic>; ContainerT = folly::fbvector<unsigned char>; bool IsRangeCheckEnabled = true]’
  938 |                         res = std::move(func(index_ptr,
      |                         ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
  939 |                                              sub_batch_size,
      |                                              ~~~~~~~~~~~~~~~
  940 |                                              value,
      |                                              ~~~~~~
  941 |                                              right_operand,
      |                                              ~~~~~~~~~~~~~~
  942 |                                              offsets));
```

### Steps To Reproduce

```markdown
should build successfully
```

**Comment by cydrain** [comment]
caused by PR #38535
```
commit acc8fb7af6451bf5b3b5423b8b2b0ad5e731ca57 (HEAD)
Author: Ted Xu <ted.xu@zilliz.com>
Date:   Wed Dec 25 15:30:50 2024 +0800

    enhance: eliminate compile warnings (part2) (#38535)
    
    See #38435
    
    ---------
    
    Signed-off-by: Ted Xu <ted.xu@zilliz.com>
```
