### ISSUE TITLE
[Bug]: master does not typecheck: internal/datacoord/meta_test.go references undefined getSegmentBinlogFields

### ISSUE THREAD

**Issue by czs007** [milvus-io/milvus#52271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

master @ `8a1470e202`

### Current Behavior

`internal/datacoord` does not typecheck on master, so `make static-check`, `go vet` and `go test` fail for everyone:

```
vet: internal/datacoord/meta_test.go:2362:13: undefined: getSegmentBinlogFields
```

`getSegmentBinlogFields` does not exist anywhere in the tree.

### Expected Behavior

master typechecks.

### Root cause: a semantic conflict between two PRs that were each green

This is not a mistake in either PR — two independently-correct changes break only in combination, and CI never tested the combination.

| When | What |
|---|---|
| 07-29 | #52006 forks from master at `113c23613a`. `getSegmentBinlogFields` exists in `index_inspector.go`, and the PR adds a call to it in `meta_test.go`. |
| 07-31 | #51768 merges. It replaces the binlog-fields index-eligibility check with a schema-version gate and **deletes** `getSegmentBinlogFields`, updating its own `index_inspector_test.go` accordingly. |
| 08-03 | #52006's last CI run (`ed1766e3e`) is green — correctly so: on that branch the function still exists. |
| 08-06 | #52006 is merged. The merge is a **rebase** (`95e3770aff` has a single parent), replaying the PR onto a master where the function is already gone. CI is not re-run on the rebased tree. |

The two PRs touch disjoint files (`index_inspector.go` vs `meta_test.go`), so git reports no conflict; only the Go compiler does.

The general gap: **a PR's CI result is only valid for the tree it ran on.** When tide rebases before pushing, the pushed tree is one that no CI job has ever seen. A merge queue — or re-running against the rebased tree before pushing — would have caught this.

### Steps To Reproduce

```
git checkout master
go vet -tags dynamic,test ./internal/datacoord/
```

### Milvus Log

n/a
