### ISSUE TITLE
[Bug]: build issue on macos with go 1.25

### ISSUE THREAD

**Issue by xinxinsh** [milvus-io/milvus#44038]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version:
master branch
Git Commit: 4fae074d56
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
macos 
- CPU/Memory: 
- GPU: 
- Others: 
Go Version: go version go1.25.0 darwin/arm64
```

### Current Behavior

when you build milvus master branch with:

make milvus

i got the following build error:

...skipping...
  Misses:           15842 / 19268 (82.22%)
Uncacheable calls:   9638 / 28906 (33.34%)
Local storage:
  Cache size (GiB):   1.1 /   5.0 (22.92%)
  Hits:              3182 / 17596 (18.08%)
  Misses:           14414 / 17596 (81.92%)
~/Desktop/SourceCode/milvus
Build Tag: pkg/v2.6.0-95-g4fae074d56
Build Time: 2025年 8月25日 星期一 06时33分03秒 UTC
Git Commit: 4fae074d56
Go Version: go version go1.25.0 darwin/arm64
Building Milvus ...
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [build-go] Error 1

i found pull request to fix this build issue of sonic: 
https://github.com/bytedance/sonic/pull/808

### Steps To Reproduce

```markdown
1. get lastest version of milvus
2. run 'make milvus' with default config
3. got the following build error
Build Tag: pkg/v2.6.0-95-g4fae074d56
Build Time: 2025年 8月25日 星期一 06时33分03秒 UTC
Git Commit: 4fae074d56
Go Version: go version go1.25.0 darwin/arm64
Building Milvus ...
# github.com/bytedance/sonic/internal/rt
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../../../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [build-go] Error 1
```

### Anything else?

after i upgrade the dependency of sonic from v1.13.2 to v1.14.0, this build issue can be fixed

**Comment by yanliang567** [comment]
/assign @liliu-z
please help to check the fix.

/unassign

**Comment by ducminhle** [comment]
I got the same issue when build on Ubuntu 22.04, go 1.25
```
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libknowhere_utils.a
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libdouble-conversion.so.3.2.0
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libfolly_exception_tracer_base.so.0.58.0-dev
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libgflags_nothreads.so.2.2
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libfolly.so
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libmilvus_core.so
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libevent_extra-2.1.so.7
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libevent_extra-2.1.so.7.0.1
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libdouble-conversion.so
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libdiskann.a
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/libhwloc.so.15
-- Up-to-date: /home/ubuntu/milvus/internal/core/output/lib/librocksdb.so
make[1]: Leaving directory '/home/ubuntu/milvus/cmake_build'
Summary:
  Hits:             486 / 3322 (14.63 %)
    Direct:         303 / 3322 (9.12 %)
    Preprocessed:   183 / 3019 (6.06 %)
  Misses:          2836
    Direct:        3019
    Preprocessed:  2836
  Uncacheable:       51
Primary storage:
  Hits:             789 / 6644 (11.88 %)
  Misses:          5855
  Cache size (GB): 1.80 / 5.00 (35.94 %)

Use the -v/--verbose option for more details.
~/milvus
Build Tag: pkg/v2.6.0-dev
Build Time: Sat Sep 20 17:17:27 UTC 2025
Git Commit: 4def0255a9
Go Version: go version go1.25.1 linux/amd64
Building Milvus ...
# github.com/bytedance/sonic/internal/rt
../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:33:22: undefined: GoMapIterator
../go/pkg/mod/github.com/bytedance/sonic@v1.13.2/internal/rt/stubs.go:36:54: undefined: GoMapIterator
make: *** [Makefile:93: build-go] Error 1
```

**Comment by xiaofan-luan** [comment]
@ducminhle could you try to upgade to sonic 1.14 see it works? 
saw this pr https://github.com/bytedance/sonic/pull/808
