### ISSUE TITLE
Query Coord/Node crashes on a daily basis when using external kafka and s3 

### ISSUE THREAD

**Issue by yovelcohen** [milvus-io/milvus#20792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.1.2
- Deployment mode(standalone or cluster): cluster (k8s)
- SDK version(e.g. pymilvus v2.0.0rc2): pymilvus 2.1.3
- OS(Ubuntu or CentOS): centOS
- CPU/Memory: 4/32GB
```

### Current Behavior

We've been running with milvus for a few weeks now. we've noticed that after some time (could be hours/days, inconsistent) the query coord/nodes start to crash.

the most notable errors we see in the logs are:
```
sealed segment has been exist on query node, segmentID is <>
```
and the segmentID changes a lot. if I delete all nodes in the cluster, than delete EVERYTHING from s3, milvus starts working again, but that is obviously a bad solution as it means losing data. 

as backup tools are not yet ready, this blocks us from relying on milvus in production as we planned.

** it also doesn't matter if the cluster/nodes restarted or not, it can happen 

I added the logs that we saw occurring the most instead of attaching just tens of thousands of them, but I can provide more if needed.

It seems that at a certain point, for some reason, milvus loses tracks of what files it actually stores in s3 and tries to pick up irrelevant segments/collections ids, are those saved somewhere that might cause that? maybe it's etcd's PVCs that contain outdated info about segments/collections?

### Expected Behavior

query node/coord should remain stable.

### Milvus Log

```
{kubernetes:{container_name:querycoordnamespace_name:milvuspod_name:milvus-querycoord-77b4f66b6f-kghl9 } cluster:gloat-dev-eu-central-1caller:querycoord/task_scheduler.go:706error_str:sealed segment has been exist on query node, segmentID is 437555398575652865filename:/var/log/containers/milvus-querycoord-77b4f66b6f-kghl9_milvus_querycoord-0d4570c3ca6f591cf7b2b9428cd1ba805aca6c6539b1ed4b84462548bfbc866f.logstream:stdoutlevel:WARNtriggerTaskID:437568876462024700time:2022/11/23 09:43:02.625 +00:00message:scheduleLoop: process triggerTask failedenv_type:dev}



{kubernetes:{container_name:querycoordnamespace_name:milvuspod_name:milvus-querycoord-77b4f66b6f-kghl9}cluster:gloat-dev-eu-central-1stack:github.com/milvus-io/milvus/internal/querycoord.(*handoffTask).execute
/go/src/github.com/milvus-io/milvus/internal/querycoord/task.go:1785
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).processTask
/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:593
github.com/milvus-io/milvus/internal/querycoord.(*TaskScheduler).scheduleLoop
/go/src/github.com/milvus-io/milvus/internal/querycoord/task_scheduler.go:678level:ERRORmessage:handoffTask: handoff segment failedcaller:querycoord/task.go:1785error_str:sealed segment has been exist on query node, segmentID is 437551646521950209filename:/var/log/containers/milvus-querycoord-77b4f66b6f-kghl9_milvus_querycoord-0d4570c3ca6f591cf7b2b9428cd1ba805aca6c6539b1ed4b84462548bfbc866f.logstream:stdoutsegmentID:437551646521950200time:2022/11/23 09:44:27.221 +00:00env_type:dev}


{kubernetes:{container_name:datanodenamespace_name:milvuspod_name:milvus-datanode-c7ddcddf4-b5g64}cluster:gloat-dev-eu-central-1stack:github.com/milvus-io/milvus/internal/datanode.(*SegmentReplica).getCollectionSchema
/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:758
github.com/milvus-io/milvus/internal/datanode.newReplica
/go/src/github.com/milvus-io/milvus/internal/datanode/segment_replica.go:202
github.com/milvus-io/milvus/internal/datanode.(*flowgraphManager).addAndStart
/go/src/github.com/milvus-io/milvus/internal/datanode/flow_graph_manager.go:50
github.com/milvus-io/milvus/internal/datanode.(*DataNode).handlePutEvent
/go/src/github.com/milvus-io/milvus/internal/datanode/data_node.go:376
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).retryHandlePutEvent
/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:88
github.com/milvus-io/milvus/internal/datanode.(*channelEventManager).Run.func1
/go/src/github.com/milvus-io/milvus/internal/datanode/event_manager.go:70caller:datanode/segment_replica.go:758error_str:describe collection 437273819624767489 from rootcoord wrong: DescribeCollection failed: can't find collection id : 437273819624767489filename:/var/log/containers/milvus-datanode-c7ddcddf4-b5g64_milvus_datanode-c3ee10223406a1713b07a6c1df99ea430fa9404466cefd14a97153440fec593c.logstream:stdoutlevel:ERRORtime:2022/11/23 09:44:41.311 +00:00message:Grpc errorenv_type:dev}


{kubernetes:{container_name:rootcoordnamespace_name:milvuspod_name:milvus-rootcoord-6bbc98cdff-cvnnx}cluster:gloat-staging-eu-central-1caller:rootcoord/timeticksync.go:323filename:/var/log/containers/milvus-rootcoord-6bbc98cdff-cvnnx_milvus_rootcoord-75fea1d64f8b2fb1c54c4f64ec88089768dbe072b9b0316cbdc79fcde0dec125.logstream:stdoutlevel:WARNtime:2022/11/23 09:46:02.472 +00:00message:rootcoord send tt to all channels too slowlyenv_type:stagingchanNum:66span:382}


{kubernetes:{container_name:rootcoordnamespace_name:milvuspod_name:milvus-rootcoord-6bbc98cdff-cvnnx}cluster:gloat-staging-eu-central-1caller:rootcoord/timeticksync.go:323filename:/var/log/containers/milvus-rootcoord-6bbc98cdff-cvnnx_milvus_rootcoord-75fea1d64f8b2fb1c54c4f64ec88089768dbe072b9b0316cbdc79fcde0dec125.logstream:stdoutlevel:WARNtime:2022/11/23 09:46:02.472 +00:00message:rootcoord send tt to all channels too slowlyenv_type:stagingchanNum:66span:382}


{kubernetes:{container_name:datacoordnamespace_name:milvuspod_name:milvus-datacoord-557998df68-jqr52}cluster:gloat-staging-eu-central-1caller:grpcclient/client.go:251error_str:err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
, /go/src/github.com/milvus-io/milvus/internal/util/trace/stack_trace.go:51 github.com/milvus-io/milvus/internal/util/trace.StackTrace
/go/src/github.com/milvus-io/milvus/internal/util/grpcclient/client.go:250 github.com/milvus-io/milvus/internal/util/grpcclient.(*ClientBase).ReCall
/go/src/github.com/milvus-io/milvus/internal/distributed/datanode/client/client.go:153 github.com/milvus-io/milvus/internal/distributed/datanode/client.(*Client).FlushSegments
/go/src/github.com/milvus-io/milvus/internal/datacoord/session_manager.go:136 github.com/milvus-io/milvus/internal/datacoord.(*SessionManager).execFlush
/usr/local/go/src/runtime/asm_amd64.s:1371 runtime.goexit
filename:/var/log/containers/milvus-datacoord-557998df68-jqr52_milvus_datacoord-44824e9ab4004b64ce9b903267b6dcd529fd6ab42472731b6945601558f18ccf.logstream:stdoutlevel:WARNtime:2022/11/23 09:47:10.612 +00:00message:datanode ClientBase ReCall grpc first call get errorenv_type:staging}


{kubernetes:{container_name:datacoordnamespace_name:milvuspod_name:milvus-datacoord-58f6db5687-fg9bb}cluster:gloat-staging-us-east-1caller:timerecord/time_recorder.go:112filename:/var/log/containers/milvus-datacoord-58f6db5687-fg9bb_milvus_datacoord-9acb7f9e86b39388d75341c4c9acc2e5d630dabe06c1105ad10a8adf7a963003.logstream:stdoutlevel:WARNtime:2022/11/23 09:46:44.432 +00:00message:Datacoord haven't received tt for 2.000000 minutesenv_type:staging}


{kubernetes:{container_name:querycoordnamespace_name:milvuspod_name:milvus-querycoord-57696b54c-jtvfx}cluster:gloat-staging-eu-central-1replica:437514449163936640level:WARNcollection:437525361045536800message:loadBalanceSegmentLoop: get node info from QueryNode failedcaller:querycoord/query_coord.go:617error_str:getNodeInfo: queryNode is offlinefilename:/var/log/containers/milvus-querycoord-57696b54c-jtvfx_milvus_querycoord-2f2f4023fc7cf3af75f75b6c9864c05182e8b69940fbc519c4ce7decd9787985.logstream:stdouttime:2022/11/23 09:46:42.222 +00:00nodeID:53env_type:staging}
```

**Comment by yanliang567** [comment]
@yovelcohen thanks for the issue. could you please upload all the log files?

**Comment by yovelcohen** [comment]
also seeing a lot of:
cannot find segment 437643111909031938 in all flowgraphs now

**Comment by yanliang567** [comment]
@yovelcohen a few quick questions:
1. If you don't have a release name, how did you install milvus, could you please share more details? 
2. calc_distance is an independent function that you can copy it out of the pymilvus, that's not a problem.
3. Try to release the collection, drop the index, rebuild the index and reload the collection if you can not search after upgrading from 2.1.x to 2.2.0.
4. how frequent do you write the collections in milvus, and what is the size of data of the writing? 

Also could you please upload the logs of querycoord, querynode and proxy pod ?

**Comment by yanliang567** [comment]
@yovelcohen it is hard to tell the reason and offer solutions without full milvus logs. 
@LoveEachDay any ideas about how to collect logs in this case? 
@xiaofan-luan
