### PR TITLE
fix: fix compilation error in ExecPlanNodeVisitor for element-level query

### PR DESCRIPTION
**Pull request by xiaofan-luan**
## Summary

- Fix master branch compilation error introduced by PR #47906
- `QueryContext::element_level_query()` does not exist, replaced with `bitset_is_element_level()` which is the correct method defined in `QueryContext.h`

## Test plan

- [ ] CI build passes (currently master is broken)
- [ ] Existing StructArray e2e tests pass

issue: #48253

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Review by SpadeA-Tang — COMMENTED** [review]
/lgtm
