### PR TITLE
fix: [cp3.0] stop logging encryption key and storage credentials in compaction logs

### PR DESCRIPTION
**Pull request by bigsheeper**
Cherry-pick from master

pr: #53191
issue: #53190

## Summary

Cherry-picked from master PR #53191 (merged). Applied cleanly with no conflicts; the per-file diff of the cherry-picked commit is identical to the master PR.

Rebased onto the latest `3.0`.

## One extra commit, not in the master PR

`internal/compaction/params_test.go` calls `mlog.CaptureGlobalLogs`, which lives
in `pkg/mlog/test_sink.go`. That file was added on master by #52510 and never
back-ported, so the cherry-pick alone does not build on 3.0:

```
internal/compaction/params_test.go:71:15: undefined: mlog.CaptureGlobalLogs
FAIL github.com/milvus-io/milvus/internal/compaction [build failed]
```

A second commit back-ports `pkg/mlog/test_sink.go` and `pkg/mlog/test_sink_test.go`
verbatim from master at `786bd20d39` (#52510). Both files are test-only; there is
no production code change beyond the cherry-picked #53191 diff.

## Verification

- [x] Cherry-picked commit's per-file diff is byte-identical to master PR #53191 (4 files, +124/-2)
- [x] No conflict markers
- [x] `go test -tags dynamic,test -gcflags="all=-N -l" -count=1 ./internal/compaction/...` — ok
- [x] `go test -tags dynamic,test -gcflags="all=-N -l" -count=1 -race ./pkg/mlog/...` — ok
- [x] `go vet -tags dynamic,test ./internal/datanode/compactor/...` — clean

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_01AZK5aCRZLovav7nKdtNYfo

### CODE REVIEW

**Review by czs007 — APPROVED** [review]
/lgtm
