### PR TITLE
test: fix SegmentChunkReaderTest build after the GetDataScanResources signature change

### PR DESCRIPTION
**Pull request by czs007**
master no longer compiles the C++ unit tests:

```
internal/core/src/segcore/SegmentChunkReaderTest.cpp:391:5: error: invalid covariant return type for
'virtual std::pair<std::shared_ptr<milvus::ChunkedColumnInterface>, std::shared_ptr<const milvus::SkipIndex> >
milvus::segcore::{anonymous}::ReaderStringSnapshot::GetDataScanResources(milvus::FieldId) const'
internal/core/src/segcore/SegmentInterface.h:122:5: note: overridden function is
'virtual std::pair<std::shared_ptr<milvus::ChunkedColumnInterface>, milvus::FieldSkipMetricsView>
milvus::segcore::SegmentReadSnapshot::GetDataScanResources(milvus::FieldId) const'
```

#53413 added the `ReaderStringSnapshot` test double against a base that did not include #51441 yet, and #51441 changed the second element of `GetDataScanResources` from `std::shared_ptr<const SkipIndex>` to `FieldSkipMetricsView`. Each PR was green on its own, and the build broke once both were on master.

The test double now returns an empty `FieldSkipMetricsView`, which, like the previous `nullptr`, means no skip metrics. It is the only remaining implementation with the old signature.

Verified on master `310377af4a`: the C++ build with unit tests (`build-cpp-with-unittest`) succeeds, and `all_tests --gtest_filter='*SegmentChunkReader*'` passes (44 tests, including `SegmentChunkReaderStringTest.StringAccessorsUseBoundSnapshot`, which uses this test double).

### CODE REVIEW

**Review by liliu-z — COMMENTED** [review]
/lgtm
/approve
