### ISSUE TITLE
build using docker ubuntu18.04 build env with error

### ISSUE THREAD

**Issue by cocodee** [milvus-io/milvus#4775]
**Please state your issue using the following template and, most importantly, in English.**

**Describe the bug**
build docker_env images using docker/cpu/ubuntu18.04/Dockerfile
and then run ./build.sh under core
Meet below failure message:
FaissException.cpp:(.text+0x279): undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()'

**Steps/Code to reproduce behavior**
Follow this [guide](http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Method of installation**
- [ ] Docker/cpu
- [ ] Docker/gpu
- [ ] Build from source

**Environment details**
- Hardware/Softwars conditions (OS, CPU, GPU, Memory)

- Milvus version (master or released version)

**Configuration file**
Settings you made in `server_config.yaml` or `milvus.yaml`

```yaml
paste-file-content-here
```

**Screenshots**

**Additional context**

**Comment by yhmo** [comment]
Looks like the gcc version is too old.
Firstly check the version of gcc:
`gcc --version`

**Comment by cocodee** [comment]
using docker/cpu/ubuntu18.04/Dockerfile docker images fix this

**Comment by cocodee** [comment]
using docker/cpu/ubuntu18.04/Dockerfile docker images fix this
