### ISSUE TITLE
[Bug]: C++ core fails to build on macOS after async packed scalar index loading

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus#53690]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Environment

```markdown
- Milvus version: master (commit d510696ac2）
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

`make build-cpp` fails to compile the C++ core on macOS. Two translation units under `internal/core/src/index/` fail:

**1. `BitmapIndex.cpp:1716` and `BitmapIndex.cpp:1842`**

```
/Users/congqi.xia/workspace/milvus/internal/core/src/index/BitmapIndex.cpp:1716:46: error: use of undeclared identifier 'POSIX_FADV_DONTNEED'
 1716 |                 raw_file.Descriptor(), 0, 0, POSIX_FADV_DONTNEED);
      |                                              ^
/Users/congqi.xia/workspace/milvus/internal/core/src/index/BitmapIndex.cpp:1842:46: error: use of undeclared identifier 'POSIX_FADV_DONTNEED'
```

**2. `IndexFactory.cpp`** — `SaturatingAdd` / `SaturatingMultiply` template deduction failures at 10 call sites (lines 934, 942, 947, 961, 962, 969, 1013, 1022, 1028, 1040):

```
/Users/congqi.xia/workspace/milvus/internal/core/src/index/IndexFactory.cpp:934:25: error: no matching function for call to 'SaturatingMultiply'
  934 |                         SaturatingMultiply(slice.plaintext_bytes, uint64_t{2}));
      |                         ^~~~~~~~~~~~~~~~~~
/Users/congqi.xia/workspace/milvus/internal/core/src/common/Utils.h:514:1: note: candidate template ignored: deduced conflicting types for parameter 'T' ('size_t' (aka 'unsigned long') vs. 'uint64_t' (aka 'unsigned long long'))
```

The build then aborts:

```
make: *** [build-cpp] Error 1
```

### Expected Behavior

The C++ core should build on macOS (Apple Silicon) with clang 19. macOS core builds are supported (`#50616` "support building core on macOS (Apple Silicon) with clang 19").

### Steps To Reproduce

```markdown
N/A (compile-time failure). See `compile.log` for the full output.
```

### Anything else?

- Introduced by PR #53483 (`enhance: load packed scalar indexes asynchronously`). The failing code was added there: the `posix_fadvise` cache-eviction calls in `BitmapIndex.cpp` and the 42 `SaturatingAdd`/`SaturatingMultiply` call sites in `IndexFactory.cpp`.
- Prior macOS build fixes `#53370` and `#53376` only touched `HybridScalarIndexTest.cpp` and `LoadAdmissionController.cpp` and do not cover these files.
- Root causes:
  - `POSIX_FADV_DONTNEED` (and `posix_fadvise(2)`) are Linux-only; the macOS SDK provides neither. macOS equivalent is `fcntl(fd, F_NOCACHE)`.
  - On macOS arm64, `size_t` is `unsigned long` while `uint64_t` is `unsigned long long` — distinct types. `SaturatingAdd(T, T)` / `SaturatingMultiply(T, T)` in `common/Utils.h` require both operands to share a single `T`, so the mixed `size_t`/`uint64_t` byte-accounting call sites fail deduction. On Linux LP64 both are `unsigned long`, which is why CI never caught it.
- Fix is prepared on branch `fix/macos-async-index-build`.
