### ISSUE TITLE
[Bug]: help wanted to compile on milvus 2.3.0

### ISSUE THREAD

**Issue by cheetahsec** [milvus-io/milvus#26646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: 2.3.0
- Deployment mode(standalone or cluster):
- MQ type(rocksmq, pulsar or kafka):    
- SDK version(e.g. pymilvus v2.0.0rc2):
- OS(Ubuntu or CentOS): ubuntu 20.04
- CPU/Memory: 
- GPU: 
- Others: go version go1.13.8 linux/amd64
```

### Current Behavior

从源码构建milvus 2.3.0，最初碰到以下问题:
`Generate proto ...
Installing protoc-gen-go
can't load package: package github.com/golang/protobuf/protoc-gen-go@v1.3.2: can only use path@version syntax with 'go get'
make: *** [Makefile:150: generated-proto] Error 1`

将'go install'指令替换为'go get‘，但是最后步骤出现问题，似乎是pulsarctl的依赖问题，希望能得到一点帮助提示
`go: github.com/milvus-io/milvus/pkg@v0.0.1 requires
        github.com/streamnative/pulsarctl@v0.5.0: github.com/streamnative/pulsarctl(v0.5.0) depends on excluded github.com/apache/pulsar-client-go/oauth2(v0.0.0-20211108044248-fe3b7c4e445b) with no newer version available
make: *** [Makefile:36: milvus] Error 1`

**Comment by cheetahsec** [comment]
非常感谢，之前记错了go的版本，切换为1.18可以继续编译，但是遇到另外一个问题，和re2关联：
`Build Tag: v2.2-testing-20230824-5-gf31c6786a-dev
Build Time: Mon Aug 28 14:14:30 UTC 2023
Git Commit: f31c6786a
Go Version: go version go1.18.1 linux/amd64
Building Milvus ...
# github.com/milvus-io/milvus/internal/util/metrics
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_stringpiece(char const*, unsigned long, void*)'
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_string(char const*, unsigned long, void*)'
collect2: error: ld returned 1 exit status
# github.com/milvus-io/milvus/internal/util/initcore
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_stringpiece(char const*, unsigned long, void*)'
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_string(char const*, unsigned long, void*)'
collect2: error: ld returned 1 exit status
# github.com/milvus-io/milvus/internal/util/indexcgowrapper
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_stringpiece(char const*, unsigned long, void*)'
/usr/bin/ld: /mnt/k/xxx/milvus/internal/core/output/lib/libmilvus_storage.so: undefined reference to `re2::RE2::Arg::parse_string(char const*, unsigned long, void*)'
collect2: error: ld returned 1 exit status
make: *** [Makefile:36: milvus] Error 2`

**Comment by jiaoew1991** [comment]
Hi @cheetahsec Have you installed the re2 package locally? If you have, you can delete it.

**Comment by jiaoew1991** [comment]
I suggest using a Docker development environment, which can reduce such compilation issues.

**Comment by cheetahsec** [comment]
@jiaoew1991 Thank you for your suggestion
