### ISSUE TITLE
[Bug]: Fail to pass CI when upgrading pymilvus version to 2.2.10.dev1

### ISSUE THREAD

**Issue by NicoYuan1986** [milvus-io/milvus#24754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Environment

```markdown
- Milvus version: bd3f0d2
- Deployment mode(standalone or cluster): standalone
- MQ type(rocksmq, pulsar or kafka):     rocksmq
- SDK version(e.g. pymilvus v2.0.0rc2): 2.2.10.dev1
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

### Current Behavior

Fail to pass CI when upgrading pymilvus version to 2.2.10.dev1.
```
2023-06-08T03:13:08.944Z] [2023-06-08 03:12:57 - ERROR - ci_test]: Traceback (most recent call last):

[2023-06-08T03:13:08.944Z]   File "/home/jenkins/agent/workspace/tests/python_client/utils/api_request.py", line 29, in inner_wrapper

[2023-06-08T03:13:08.944Z]     res_str = str(res)

[2023-06-08T03:13:08.944Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 126, in __repr__

[2023-06-08T03:13:08.944Z]     return str(self.to_dict())

[2023-06-08T03:13:08.944Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 217, in to_dict

[2023-06-08T03:13:08.944Z]     "auto_id": self.auto_id,

[2023-06-08T03:13:08.944Z]   File "/usr/local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 200, in auto_id

[2023-06-08T03:13:08.944Z]     return self.primary_field.auto_id

[2023-06-08T03:13:08.944Z] AttributeError: 'NoneType' object has no attribute 'auto_id'

[2023-06-08T03:13:08.944Z]  (api_request.py:39)

[2023-06-08T03:13:08.944Z] [2023-06-08 03:12:57 - ERROR - ci_test]: (api_response) : 'NoneType' object has no attribute 'auto_id' (api_request.py:40)
```

### Expected Behavior

pass

### Milvus Log

https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-24732/1/pipeline/110/

**Comment by NicoYuan1986** [comment]
Fixed.

**Comment by NicoYuan1986** [comment]
https://jenkins.milvus.io:18080/blue/organizations/jenkins/Milvus%20HA%20CI/detail/PR-24880/1/pipeline/110/

master branch 2.4.0.dev70 , reproduce.

**Comment by NicoYuan1986** [comment]
@czs007  Could you help fix it in master, thx!

**Comment by XuanYang-cn** [comment]
/assing @NicoYuan1986
should be fixed in master

**Comment by NicoYuan1986** [comment]
Fixed.
