### PR TITLE
enhance: [cp2.6] batch backport highlight row invariant and import retry backoff

### PR DESCRIPTION
**Pull request by bigsheeper**
Unified batch backport to 2.6 (one CP PR instead of two, to reduce CI load). One commit per master PR, cherry-picked in master merge order.

pr: #51575
pr: #51823
issue: #51574
issue: #51824

Supersedes closed per-PR CP PRs: #52412, #52428 (identical resolved content, verified line-by-line against each master PR diff).

## Included enhancements (cherry-pick order)

1. #51575 — enforce row-count invariant for semantic highlight inputs (guards an out-of-range on nullable/dynamic text fields). Clean pick, no adaptation.
2. #51823 — configurable backoff for import write retry. 2.6 adaptation: test imports normalized to `pkg/v2` (unused master-only imports dropped); paramtable formatter warns use 2.6's `log.Warn`.

## Verification

- [x] Each commit's changed lines verified identical to the individually-reviewed CP commits (which were line-level compared against their master PR diffs)
- [x] No conflict markers
- [ ] make static-check (skipped by cherry-pick workflow)

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by bigsheeper** [comment]
Force-pushed a CI fix.

**#51575 commit** — `highlighter.go` failed to compile on 2.6:
```
internal/proxy/highlighter.go:551:33: undefined: resultData
→ FAIL internal/distributed/proxy [build failed]
```
On master, `semanticHighlightOperator.run` had already been refactored to hoist `resultData := result.GetResults()`; on 2.6 that function still reads `result.Results` directly, so the cherry-picked line referenced a variable that does not exist in this scope. Changed to `searchResultHitCount(result.GetResults())` — same type contract as the pre-existing `lexicalHighlightOperator.run` on this branch (line 389/401), which already calls the helper with `result.GetResults()`.

The #51823 commit is untouched (verified line-by-line: zero changes).

**Review by czs007 — APPROVED** [review]
/lgtm
